# Generated by Django 3.2.16 on 2022-10-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(verbose_name='スコア')),
                ('ob', models.IntegerField(blank=True, default=0, null=True, verbose_name='OB')),
                ('penalty', models.IntegerField(blank=True, default=0, null=True, verbose_name='OB')),
                ('fw', models.IntegerField(blank=True, default=0, null=True, verbose_name='OB')),
                ('par_on', models.IntegerField(blank=True, default=0, null=True, verbose_name='OB')),
                ('patt', models.IntegerField(blank=True, default=0, null=True, verbose_name='OB')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('color', models.CharField(blank=True, choices=[('primary', 'primary'), ('secondary', 'secondary'), ('success', 'success'), ('info', 'info'), ('warning', 'warning'), ('danger', 'danger'), ('light', 'light'), ('dark', 'dark')], max_length=32, null=True, verbose_name='テーマカラー')),
            ],
        ),
    ]
