# Generated by Django 3.2.16 on 2022-10-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_auto_20221022_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='putt',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='パット数'),
        ),
    ]
