# Generated by Django 3.2.16 on 2022-10-23 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0003_alter_detail_putt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日付')),
                ('total_score', models.PositiveSmallIntegerField(verbose_name='スコア')),
                ('ob', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='OB')),
                ('penalty', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ペナルティ')),
                ('fw', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='FWキープ')),
                ('par_on', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='パーオン')),
                ('putt', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='パット数')),
            ],
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
