# Generated by Django 3.2.16 on 2022-10-24 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0004_auto_20221024_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='score.person', verbose_name='対象取引'),
            preserve_default=False,
        ),
    ]
