# Generated by Django 3.2.16 on 2022-10-24 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0005_stat_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='score.person', verbose_name='プレイヤー'),
        ),
    ]
